version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: localhost/${DEV_CONTAINER_NAME}
    container_name: ${DEV_CONTAINER_NAME}
    hostname: docker-${DEV_CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - ./.config:/root/.config

